@startuml C4_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Networking - Container Diagram

LAYOUT_WITH_LEGEND()

System_Boundary(subsys, "Networking") {
    Container(socket, "Socket", "C", "Socket layer")
    Container(tcp, "TCP", "C", "TCP protocol")
    Container(udp, "UDP", "C", "UDP protocol")
    Container(ip, "IP", "C", "IP layer")
    Container(netfilter, "Netfilter", "C", "Packet filtering")
}

System_Ext(other, "Other Subsystems")

Rel(socket, tcp, "Calls")
Rel(tcp, udp, "Calls")
Rel(udp, ip, "Calls")
Rel(ip, netfilter, "Calls")
@enduml