@startuml C4_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title File Systems - Container Diagram

LAYOUT_WITH_LEGEND()

System_Boundary(subsys, "File Systems") {
    Container(vfs, "VFS", "C", "Virtual File System layer")
    Container(namei, "Namei", "C", "Path lookup")
    Container(open, "Open", "C", "File open operations")
    Container(read_write, "Read/Write", "C", "I/O operations")
    Container(buffer, "Buffer", "C", "Buffer cache")
}

System_Ext(other, "Other Subsystems")

Rel(vfs, namei, "Calls")
Rel(namei, open, "Calls")
Rel(open, read_write, "Calls")
Rel(read_write, buffer, "Calls")
@enduml